### ISSUE TITLE
Version 1.1.0 and 1.1.1 not found in any repository

### ISSUE THREAD

**Issue by pliratu** [Explore-In-HMS/huawei.ads.ironsource_mediation#15] opened 2023-04-18 08:39 UTC
Gradle files are created according to instructions. Repositories are added to the `allprojects.repositories` block and to the `repositories` block. 

```
google()
jcenter() // Also, make sure jcenter() is included
maven { url 'https://developer.huawei.com/repo/' } //Add this line
maven {url "https://jitpack.io"} // Add this line
```

A year ago version **1.1.0** could be found (with the same configuration)
Meanwhile only version 1.0.4 is found. 1.1.0 and 1.1.1 are not found.

**Comment by Aziz-T** [comment] 2023-04-27 08:43
This issue is a problem caused by JitPack with our old versions. We will fix it as soon as possible and make it usable again.

**Comment by nostel** [comment] 2023-05-17 13:09
1.1.3 have the same problem
`> Could not resolve all artifacts for configuration ':launcher:debugRuntimeClasspath'.
   > Could not resolve com.github.Explore-In-HMS:huawei.ads.ironsource_mediation:1.1.3.
     Required by:
         project :launcher > project :unityLibrary
      > Could not resolve com.github.Explore-In-HMS:huawei.ads.ironsource_mediation:1.1.3.
         > Could not get resource 'https://aa-sdk.s3-eu-west-1.amazonaws.com/android_repo/com/github/Explore-In-HMS/huawei.ads.ironsource_mediation/1.1.3/huawei.ads.ironsource_mediation-1.1.3.pom'.
            > Could not HEAD 'https://aa-sdk.s3-eu-west-1.amazonaws.com/android_repo/com/github/Explore-In-HMS/huawei.ads.ironsource_mediation/1.1.3/huawei.ads.ironsource_mediation-1.1.3.pom'.`

**Comment by Aziz-T** [comment] 2023-06-01 14:27
All versions are now available. If you are experiencing the same error, make sure to add the following section to the repository of build.gradle in your app.
```
    repositories {
        maven { url 'https://developer.huawei.com/repo/' }
        maven {
            url 'https://android-sdk.is.com/'
        }
        maven {url "https://jitpack.io"}
    }
```

If you have any other questions, you can ask, otherwise I will close the issue.

**Closed as completed** 2023-06-08 07:29 UTC
